### ISSUE TITLE
nem2-cli のプロファイル設定が必要？

### ISSUE THREAD

**Issue by fukuro2506** [44uk/nem2-dojo#1]
以下でエラーが発生。
profile の作成が必要でしょうか？
```
$ nem2-cli monitor block
ERR To start using the nem2-cli create a default profile using: nem2-cli profile create --privatekey your_private_key --network network --url http://localhost:3000.
```

**Comment by 44uk** [comment]
プロファイルの指定が必要です。ドキュメント通りであれば `--profile alice` とすれば良いです。
`--profile` をつけなかった場合は`--profile default`とした場合と同じ動きになり、
上記の場合は`default`という名前のプロファイルがなかったためです。
指定がめんどくさいようであれば`alice`ではなく`default`としてしまってもいいと思います。

**Comment by fukuro2506** [comment]
ありがとうございます。
`default`の`profile`を作成してできました。
`alice`も用意されているのですね。確認してみます。

**Comment by 44uk** [comment]
すみません、もしかすると私が意図を読み取りそこねていたかもしれません。
ドキュメント通りの進め方だとプロファイルがまだ作成されていないため、
手順通りだとエラーになるケースがあるようですね。
修正していきます。ありがとうございました。

**Comment by fukuro2506** [comment]
はい、そうです。私も明確に伝えればよかったですね。
修正よろしくお願いします。
